name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-gnutls-dev
      - name: Install clib
        run: |
          git clone https://github.com/clibs/clib.git
          cd clib
          make
          sudo make install
      - name: Run tests
        run: make test
